### ISSUE TITLE
cannot docker build

### ISSUE THREAD

**Issue by sprinter707** [zoom/meetingsdk-linux-raw-recording-sample#13]
Hello.

I completed `cmake -B build` and I run docker build, but I got an error.

```
❯ docker build --no-cache -t msdk-6.0.2-on-centos8-compact -f Dockerfile-Centos8/Dockerfile .
[+] Building 146.6s (15/18)                                                                                   docker:default
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 1.66kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                       0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load metadata for quay.io/centos/centos:8                                                                2.9s
 => [ 1/14] FROM quay.io/centos/centos:8@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a        0.0s
 => [internal] load build context                                                                                       0.1s
 => => transferring context: 278.10kB                                                                                   0.1s
 => CACHED [ 2/14] WORKDIR /etc/yum.repos.d/                                                                            0.0s
 => [ 3/14] RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*                                           0.3s
 => [ 4/14] RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS  0.4s
 => [ 5/14] RUN yum update -y                                                                                          33.1s
 => [ 6/14] RUN yum install -y dnf-plugins-core     && dnf install -y cmake gcc gcc-c++     && dnf config-manager --s  58.3s
 => [ 7/14] RUN yum install -y glib2-devel                                                                             41.0s
 => [ 8/14] RUN yum install -y pulseaudio pulseaudio-utils                                                              5.2s
 => [ 9/14] WORKDIR /app                                                                                                0.0s
 => [10/14] COPY demo/ /app/demo/                                                                                       1.8s
 => ERROR [11/14] RUN cd /app/demo && rm -rf bin && rm -rf build && cmake -B build && cd build && make                  3.6s
------
 > [11/14] RUN cd /app/demo && rm -rf bin && rm -rf build && cmake -B build && cd build && make:
0.890 -- The CXX compiler identification is GNU 8.5.0
0.908 -- Detecting CXX compiler ABI info
1.019 -- Detecting CXX compiler ABI info - done
1.025 -- Check for working CXX compiler: /usr/bin/c++ - skipped
1.025 -- Detecting CXX compile features
1.026 -- Detecting CXX compile features - done
1.030 -- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2")
1.049 -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
1.049 -- Checking for module 'glib-2.0'
1.059 --   Found glib-2.0, version 2.56.4
1.073 -- Checking for module 'gio-2.0'
1.080 --   Found gio-2.0, version 2.56.4
1.396 -- Configuring done
1.403 -- Generating done
1.404 -- Build files have been written to: /app/demo/build
1.438 [  8%] Building CXX object CMakeFiles/meetingSDKDemo.dir/meeting_sdk_demo.cpp.o
1.934 [ 16%] Building CXX object CMakeFiles/meetingSDKDemo.dir/MeetingReminderEventListener.cpp.o
2.054 [ 25%] Building CXX object CMakeFiles/meetingSDKDemo.dir/MeetingServiceEventListener.cpp.o
2.175 [ 33%] Building CXX object CMakeFiles/meetingSDKDemo.dir/NetworkConnectionHandler.cpp.o
2.292 [ 41%] Building CXX object CMakeFiles/meetingSDKDemo.dir/AuthServiceEventListener.cpp.o
2.409 [ 50%] Building CXX object CMakeFiles/meetingSDKDemo.dir/MeetingParticipantsCtrlEventListener.cpp.o
2.444 [ 58%] Building CXX object CMakeFiles/meetingSDKDemo.dir/MeetingRecordingCtrlEventListener.cpp.o
2.476 [ 66%] Building CXX object CMakeFiles/meetingSDKDemo.dir/ZoomSDKRenderer.cpp.o
2.609 [ 75%] Building CXX object CMakeFiles/meetingSDKDemo.dir/ZoomSDKAudioRawData.cpp.o
2.737 [ 83%] Building CXX object CMakeFiles/meetingSDKDemo.dir/ZoomSDKVideoSource.cpp.o
2.932 [ 91%] Building CXX object CMakeFiles/meetingSDKDemo.dir/ZoomSDKVirtualAudioMicEvent.cpp.o
3.168 [100%] Linking CXX executable ../bin/meetingSDKDemo
3.199 /usr/bin/ld: skipping incompatible /app/demo/lib/zoom_meeting_sdk/libmeetingsdk.so when searching for -lmeetingsdk
3.199 /usr/bin/ld: cannot find -lmeetingsdk
3.199 /usr/bin/ld: skipping incompatible /app/demo/lib/zoom_meeting_sdk/libmeetingsdk.so when searching for -lmeetingsdk
3.199 /usr/bin/ld: cannot find -lmeetingsdk
3.200 collect2: error: ld returned 1 exit status
3.201 make[2]: *** [CMakeFiles/meetingSDKDemo.dir/build.make:257: ../bin/meetingSDKDemo] Error 1
3.201 make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/meetingSDKDemo.dir/all] Error 2
3.201 make: *** [Makefile:91: all] Error 2
------
Dockerfile:33
--------------------
  31 |
  32 |     # Execute additional commands
  33 | >>>  RUN cd /app/demo && rm -rf bin && rm -rf build && cmake -B build && cd build && make
  34 |
  35 |      # Set the working directory to the binary folder
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /app/demo && rm -rf bin && rm -rf build && cmake -B build && cd build && make" did not complete successfully: exit code: 2
```

how to solve this problem :( ?

**Comment by tanchunsiong** [comment]
did you copy the SDK files into this sample code?

3.199 /usr/bin/ld: skipping incompatible /app/demo/lib/zoom_meeting_sdk/libmeetingsdk.so when searching for -lmeetingsdk
3.199 /usr/bin/ld: cannot find -lmeetingsdk
3.199 /usr/bin/ld: skipping incompatible /app/demo/lib/zoom_meeting_sdk/libmeetingsdk.so when searching for -lmeetingsdk
3.199 /usr/bin/ld: cannot find -lmeetingsdk

**Comment by sprinter707** [comment]
Yes. I copied the .so files.

```
❯ ls -al
total 720600
drwxrwxr-x@ 9 jasper  staff        288  8 21 16:11 .
drwxrwxr-x@ 4 jasper  staff        128  8 20 14:45 ..
-rw-r--r--@ 1 jasper  staff       6148  8 21 16:11 .DS_Store
drwxr-xr-x@ 3 jasper  staff         96  8 20 13:43 json
-rwxr-xr-x@ 1 jasper  staff  183860952  8 20 13:42 libmeetingsdk.so
-rwxr-xr-x@ 1 jasper  staff  183860952  8 20 13:42 libmeetingsdk.so.1
-rwxr-xr-x@ 1 jasper  staff    1214824  8 20 13:42 libmpg123.so
drwxr-xr-x@ 4 jasper  staff        128  8 20 14:45 qt_libs
-rw-rw-r--@ 1 jasper  staff          0  6 21 17:36 readme.md
❯ pwd
/Users/jasper/Desktop/Workspaces/orelo-zoom-be/demo/lib/zoom_meeting_sdk
```

**Comment by sprinter707** [comment]
I solved the problem.
I use a MacBook M1 chip. This MacBook uses arm64 architecture.
But Zoom SDK supports x86_64(amd, intel chip).

Depending on the OS of the execution environment, if it is ARM64, install centos using ARM64 architecture, and download gcc and the version corresponding to ARM64.

In Dockerfile, `FROM quay.io/centos/centos:8` is  install ARM64 centOS in m1 macbook.

I change the line to `FROM --platform=linux/amd64 centos:8`.

It installs centOS using AMD64 architecture.

And change the zoom SDK version to 6.0.2.

Build success!



This causes competition issues.

**Comment by khursheed33** [comment]
Hi I am trying with SDK version on windows (using docker) 6.2.11
Getting this error:

`D:\Programs\zoom-sdk-linux>docker build -t msdk-6.0.2-on-ubuntu-compact -f Dockerfile-Ubuntu/Dockerfile .
[+] Building 18.8s (9/12)
 => [internal] load build definition from Dockerfile                                                                                     0.0s
 => => transferring dockerfile: 32B                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                        0.0s
 => => transferring context: 2B                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                          2.0s
 => [1/8] FROM docker.io/library/ubuntu:22.04@sha256:ed1544e454989078f5dec1bfdabd8c5cc9c48e0705d07b678ab6ae3fb61952d2                    0.0s
 => [internal] load build context                                                                                                        0.4s
 => => transferring context: 225.07kB                                                                                                    0.3s
 => CACHED [2/8] RUN apt-get update && apt-get install -y --no-install-recommends     build-essential     cmake     pkgconf     libx11-  0.0s
 => CACHED [3/8] WORKDIR /app                                                                                                            0.0s
 => [4/8] COPY demo/ /app/demo/                                                                                                          6.0s
 => ERROR [5/8] RUN cd /app/demo &&     rm -rf bin build &&     cmake -B build &&     cd build &&     make                              10.3s
------
 > [5/8] RUN cd /app/demo &&     rm -rf bin build &&     cmake -B build &&     cd build &&     make:
#9 2.204 -- The CXX compiler identification is GNU 11.4.0
#9 2.254 -- Detecting CXX compiler ABI info
#9 2.426 -- Detecting CXX compiler ABI info - done
#9 2.442 -- Check for working CXX compiler: /usr/bin/c++ - skipped
#9 2.444 -- Detecting CXX compile features
#9 2.449 -- Detecting CXX compile features - done
#9 2.473 -- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
#9 2.544 -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
#9 2.544 -- Checking for module 'glib-2.0'
#9 2.554 --   Found glib-2.0, version 2.72.4
#9 2.586 -- Checking for module 'gio-2.0'
#9 2.604 --   Found gio-2.0, version 2.72.4
#9 3.694 -- Configuring done
#9 3.709 -- Generating done
#9 3.710 -- Build files have been written to: /app/demo/build
#9 3.747 [  8%] Building CXX object CMakeFiles/meetingSDKDemo.dir/meeting_sdk_demo.cpp.o
#9 5.176 /app/demo/meeting_sdk_demo.cpp: In function 'void JoinMeeting()':
#9 5.176 /app/demo/meeting_sdk_demo.cpp:545:122: error: invalid new-expression of abstract class type 'MeetingServiceEventListener'
#9 5.176   545 |         m_pMeetingService->SetEvent(new MeetingServiceEventListener(&onMeetingJoined, &onMeetingEndsQuitApp, &onInMeeting)); 
#9 5.176       |                                                                                                                          ^   
#9 5.176 In file included from /app/demo/meeting_sdk_demo.cpp:30:
#9 5.176 /app/demo/MeetingServiceEventListener.h:6:7: note:   because the following virtual functions are pure within 'MeetingServiceEventListener':
#9 5.176     6 | class MeetingServiceEventListener : public ZOOM_SDK_NAMESPACE::IMeetingServiceEvent
#9 5.176       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#9 5.176 In file included from /app/demo/meeting_sdk_demo.cpp:19:
#9 5.176 /app/demo/include/h/meeting_service_interface.h:493:22: note:     'virtual void ZOOMSDK::IMeetingServiceEvent::onMeetingFullToWatchLiveStream(const zchar_t*)'
#9 5.176   493 |         virtual void onMeetingFullToWatchLiveStream(const zchar_t* sLiveStreamUrl) = 0;
#9 5.176       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#9 5.388 make[2]: *** [CMakeFiles/meetingSDKDemo.dir/build.make:76: CMakeFiles/meetingSDKDemo.dir/meeting_sdk_demo.cpp.o] Error 1
#9 5.388 make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/meetingSDKDemo.dir/all] Error 2
#9 5.388 make: *** [Makefile:91: all] Error 2
------
executor failed running [/bin/sh -c cd /app/demo &&     rm -rf bin build &&     cmake -B build &&     cd build &&     make]: exit code: 2     

D:\Programs\zoom`

**Comment by yk-recall** [comment]
Hey @khursheed33,

It looks like the build hiccup is coming from your MeetingServiceEventListener missing an implementation for onMeetingFullToWatchLiveStream, which is making it abstract. I would recommend adding an override for that method (a simple empty implementation works too) and double-check that your SDK version matches what the sample app expects.
